# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
#
orbs:
  slack: circleci/slack@4.10.1

commands:
  destroy-environments:
    description: Destroy backend and frontend cloudformation stacks .
    parameters:
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name frontend-${CIRCLE_WORKFLOW_ID:0:7} \
            & aws cloudformation delete-stack --stack-name backend-${CIRCLE_WORKFLOW_ID:0:7}

  revert-migrations:
    description: Revert database migration.
    steps:
      - restore_cache:
          keys: [backend-modules]
      - run:
          name: Revert migrations
          when: on_fail
          working_directory: ./backend
          command: |
            SUCCESS=$(curl https://kvdb.io/Lma7SCSvsHo6Cnf1weNFWx/migration_${CIRCLE_WORKFLOW_ID:0:7}?access_token=${KVDB_ACCESS_TOKEN})
            [[ $SUCCESS == 1 ]] || (exit 0) \
            && (npm install;                \
                npm run migrations:revert)
  notify-slack:
    description: notify slack
    steps:
      - slack/notify:
          channel: ${SLACK_DEFAULT_CHANNEL}
          event: fail
          template: basic_fail_1

jobs:
  ################################################# build frontend ########################################### 
  build-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build front-end
          working_directory: ./frontend
          command: |
            npm i
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
      - save_cache:
          paths: [frontend/dist]
          key: frontend-dist
      - notify-slack
  ################################################# build backend ###########################################        
  build-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run:
          name: Back-end build
          working_directory: ./backend
          command: |
            npm i
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
      - save_cache:
          paths: [backend/dist]
          key: backend-dist
      - notify-slack
  ################################################# test-frontend ###########################################
  test-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Front-end test
          working_directory: ./frontend
          command: |
            npm run test
      - notify-slack
  ################################################# test-backend ###########################################
  test-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end test
          working_directory: ./backend
          command: |
            npm run test
      - notify-slack
  ################################################# scan-frontend ###########################################
  scan-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Frontend-end audit
          working_directory: ./frontend
          command: |
            npm audit fix --audit-level=critical --force
            npm audit fix --force
            npm audit --audit-level=critical 
      - notify-slack 
  ################################################# scan-backend ###########################################
  scan-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end audit
          working_directory: ./backend
          command: |
            npm i
            npm audit fix --audit-level=critical --force
            npm audit fix --force
            npm audit --audit-level=critical
      - notify-slack
      

 ################################################# deploy-infrastructure ############################
  deploy-infrastructure:
    docker:
      # Docker image here that supports AWS CLI
      - image: cimg/aws:2022.09.1
    steps:
      # Checkout code from git
      - checkout
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --tags project=udapeople \
              --stack-name backend-${CIRCLE_WORKFLOW_ID:0:7}\
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" 
            
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --tags project=your-tag \
              --stack-name frontend-${CIRCLE_WORKFLOW_ID:0:7} \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            aws ec2 describe-instances                                            \
              --query 'Reservations[*].Instances[*].PublicIpAddress'              \
              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}"  \
              --output text >> .circleci/ansible/inventory.txt
      - persist_to_workspace:
          root: .
          paths:
            - .circleci/ansible/inventory.txt
      # Here's where you will add some code to rollback on failure 
      - destroy-environments
      - notify-slack
        
  ################################################# configure-infrastructure #####################################
  configure-infrastructure:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["59:98:8e:04:2a:4b:b1:b5:9c:fd:e5:46:d8:d3:fe:a1"]
      - attach_workspace:
          at: .
      - run:
          name: install pip3
          command: |
            sudo apt update 
            sudo apt install python3-pip -y
            pip3 install --upgrade pip
      - run:
          name: Install ansible
          command: |
            pip3 install ansible 
      - run:
          name: Configure server
          working_directory: ./.circleci/ansible
          command: |
            ansible-playbook -i inventory.txt configure-server.yml

      - notify-slack
######################################## run-migrations ######################
  run-migrations:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build] 
      - restore_cache:
          keys: [backend-dist]
      - attach_workspace:
          at: .
      - run:
          name: Install dependency
          command: |
            sudo apt update -y
            sudo apt upgrade -y
            sudo apt update -y
            sudo apt install python3-pip -y
            pip3 install --upgrade pip
      - run:
          name: install awscli
          command: |
            pip3 install awscli
      - run:
          name: Run migrations
          working_directory: ./backend
          command: |
            npm install
            npm run migrations | tee -a migrations_output.txt  
      - run:
          name: Send migration results to kvdb
          working_directory: ./backend
          command: |
            grep "has been executed successfully" migrations_output.txt || (exit 1)                       
            curl https://kvdb.io/Lma7SCSvsHo6Cnf1weNFWx/migration_${CIRCLE_WORKFLOW_ID:0:7}?access_token=${KVDB_ACCESS_TOKEN} -d '1'

      - destroy-environments
      - revert-migrations
      - notify-slack

  ######################################## deploy-frontend ######################
  deploy-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Get backend url
          command: |
            sudo apt update
            sudo apt upgrade -y
            sudo apt install python3-pip -y
            pip3 install --upgrade pip
      - run:
          name: Get backend url
          command: |
            pip3 install awscli
      - run:
          name: Get backend url
          command: |
            export BACKEND_IP=$(aws ec2 describe-instances                          \
                --query 'Reservations[*].Instances[*].PublicIpAddress'              \
                --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}"  \
                --output text)
            export API_URL="http://${BACKEND_IP}:3030"
            echo API_URL="http://${BACKEND_IP}:3030" > frontend/.env
      - persist_to_workspace:
          root: .
          paths:
            - frontend/.env
      - run:
          name: Deploy frontend objects
          working_directory: ./frontend
          command: |
            npm i
            npm run build
            aws s3 cp ./dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
      - run:
          name: Get S3 url resulting from frontend deployment
          command: |
            aws cloudformation --region ${AWS_DEFAULT_REGION} describe-stacks   \
              --stack-name "frontend-${CIRCLE_WORKFLOW_ID:0:7}"       \
              --query "Stacks[0].Outputs[?OutputKey=='WebsiteURL'].OutputValue" \
              --output text
      - run:
          name: Empty s3 bucket.
          when: on_fail
          command: |
            aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
      - destroy-environments          
      - revert-migrations
      - notify-slack

#################################  deploy-backend ##########################################
  deploy-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["59:98:8e:04:2a:4b:b1:b5:9c:fd:e5:46:d8:d3:fe:a1"]
      - attach_workspace:
          at: .
      - run:
          name: install pip
          command: |
            sudo apt update 
            sudo apt upgrade -y
            sudo apt install python3-pip -y
            pip3 install --upgrade pip
      - run:
          name: install awscli
          command: |
            pip3 install awscli
      - run:
          name: install ansible
          command: |
            pip3 install ansible
      - run:
          name: Backend final build.
          working_directory: .
          command: |
            cd backend
            npm i
            npm run build
            cd ..
            sudo tar -czvf mybackend.tar.gz backend/
            
      - run:
          name: Deploy backend
          working_directory: ./.circleci/ansible
          command: |
            echo "Contents  of the inventory.txt file are -------"
            cat inventory.txt
            ansible-playbook -i inventory.txt deploy-backend.yml
      - run:
          name: Empty s3 bucket.
          when: on_fail
          command: |
            aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
      - destroy-environments
      - revert-migrations
      - notify-slack

  ######################################  somke-test #################################
  smoke-test:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: install pip
          command: |
            sudo apt update 
            sudo apt upgrade -y
            sudo apt install python3-pip -y
            pip3 install --upgrade pip
      - run:
          name: install awscli
          command: |
            pip3 install awscli
      - run:
          name: backend smoke-test
          working_directory: ./frontend
          command: |
            source .env
            echo ${API_URL}
            curl "${API_URL}/api/status" | tee apistatus.txt
            cat apistatus.txt | grep "ok" || exit 1
      - run:
          name: Frontend smoke test
          command: |
            curl -s "http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-${AWS_DEFAULT_REGION}.amazonaws.com/#/employees" | tee apistatus.txt 
            cat apistatus.txt | grep "Welcome" || exit 1
      - run:
          name: Empty s3 bucket.
          when: on_fail
          command: |
            aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
      - destroy-environments
      - revert-migrations
      - notify-slack
      
  ##################################### 
  get_last_deployment_id:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar gzip
      - run:
          name: Fetch and save the old pipeline ID (bucket name) responsible for the last release.
          command: |
            aws cloudformation \
            list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
            --no-paginate --output text > ~/textfile.txt   
            cat ~/textfile.txt
      - persist_to_workspace:
          root: ~/
          paths: 
            - textfile.txt 
      - slack/notify:
          channel: ${SLACK_DEFAULT_CHANNEL} #circleci_project
          event: fail
          template: basic_fail_1
      - notify-slack

  #################################### cloudfront-update ########################
  cloudfront-update:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Execute cloudfront.yml
          command: |
            aws cloudformation deploy \
            --template-file .circleci/files/cloudfront.yml \
            --stack-name InitialStack-${CIRCLE_WORKFLOW_ID:0:7} \
            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}"
      - run:
          name: Empty s3 bucket.
          when: on_fail
          command: |
            aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
      - destroy-environments
      - revert-migrations
      - notify-slack
  ####################################### clean_up_old_front_end ##########################
  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar gzip
      - run:
          name: final cleanup on success
          command: |
            echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
            export S3LIST="$(aws s3 ls)"
            export CurrentS3="$(aws s3 ls | grep ${CIRCLE_WORKFLOW_ID:0:7}) " 
            echo Stack names: "${STACKS[@]}"
            echo S3LIST names: "${S3LIST[@]}"

            for s3bucket in "${S3LIST[@]}"
            do
              if [[ "${s3bucket}" != "${CurrentS3}" ]] 
              then
                aws s3 rm s3://"${s3bucket}" --recursive
              else
                echo "nothing to cleanup"
              fi
            done

            for st in "${STACKS[@]}"
            do
              if [[ "${st}" != "frontend-${CIRCLE_WORKFLOW_ID:0:7}" ]] || [[ "${st}" != "backend-${CIRCLE_WORKFLOW_ID:0:7}" ]] || [[ "${st}" != "InitialStack-${CIRCLE_WORKFLOW_ID:0:7}" ]]
              then
                aws cloudformation delete-stack --stack-name "${st}"
              else
                echo "nothing to cleanup"
              fi
            done
      - notify-slack  
  #===================================================================================#  
workflows:
  default:
    jobs:
      # - build-frontend
      # - build-backend
      # - test-frontend:
      #     requires: [build-frontend]
      # - test-backend:
      #     requires: [build-backend]
      # - scan-backend:
      #     requires: [build-backend]
      # - scan-frontend:
      #     requires: [build-frontend]
      # - deploy-infrastructure:
      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
      # - configure-infrastructure:
      #     requires: [deploy-infrastructure]
      # - run-migrations:
      #     requires: [configure-infrastructure]
      # - deploy-frontend:
      #     requires: [run-migrations]
      # - deploy-backend:
      #     requires: [run-migrations]
      # - smoke-test:
      #    requires: [deploy-frontend,deploy-backend]
      # - cloudfront-update:
      #     requires: [smoke-test,deploy-frontend,deploy-backend]
      # - get_last_deployment_id:
      #     requires: [cloudfront-update]
      - clean_up_old_front_end
      #   requires: [get_last_deployment_id]
      


